name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Upload Static HTML Files
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_06D5FD503 }}
          action: "upload"
          app_location: "/"           # Root folder where your index.html lives
          output_location: "/"        # No build folder – use same
          skip_app_build: true        # <--- this skips the whole Oryx nonsense
          github_id_token: ${{ steps.idtoken.outputs.result }}

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const core = require('@actions/core')
            return await core.getIDToken()
          result-encoding: string
